spring:
    datasource:
        url: jdbc:mysql://localhost:3306/todo_db
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: "root"
        password: "root"
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        generate-ddl: true
    flyway:
        baseline-on-migrate: true
